//config/simulationBodyConfig.js
export const simulationBodyConfigs = [
  {
    name: "Sun",
    kind: "star",
    visualRole: "sun",

    orbitalDistanceAu: 0,
    physicalRadiusKm: 696340,

    distance: 0,

    rotationSpeed: 0.12,

    dayHours: 609.12,
    tiltDeg: 7.25,

    texture: "./textures/2k_sun.jpg",
    color: 0xffcc66,

    hasOrbitRing: false,
    hasLabel: true,
  },
  {
    name: "Mercury",
    kind: "planet",
    visualRole: "planet",

    physicalRadiusKm: 2439.7,
    orbitalDistanceAu: 0.387,
    yearDays: 88,
    dayHours: 1407.6,
    tiltDeg: 0.03,
    orbitalInclinationDeg: 7.0,
    orbitalAscendingNodeDeg: 48.3,
    texture: "./textures/2k_mercury.jpg",
    color: 0xb3a28a,
    hasOrbitRing: true,
    hasLabel: true,
  },
  {
    name: "Venus",
    kind: "planet",
    visualRole: "planet",

    physicalRadiusKm: 6051.8,
    orbitalDistanceAu: 0.723,
    yearDays: 224.7,
    dayHours: -5832.5,
    tiltDeg: 177.4,

    orbitalInclinationDeg: 3.395,
    orbitalAscendingNodeDeg: 76.68,
    texture: "./textures/2k_venus_atmosphere.jpg",
    color: 0xd2a86b,
    hasOrbitRing: true,
    hasLabel: true,
  },
  {
    name: "Earth",
    kind: "planet",
    visualRole: "planet",

    physicalRadiusKm: 6371.0,
    orbitalDistanceAu: 1.0,
    yearDays: 365.25,
    dayHours: 23.93,
    tiltDeg: 23.44,
    orbitalInclinationDeg: 0.0,
    orbitalAscendingNodeDeg: 0.0,
    texture: "./textures/land_ocean_ice_cloud_2048.jpg",
    color: 0x4f86ff,
    hasOrbitRing: true,
    hasLabel: true,
  },
  {
    name: "Moon",
    kind: "satellite",
    parentName: "Earth",
    visualRole: "moon",

    physicalRadiusKm: 1737.4,
    parentOrbitDistanceKm: 384400,
    yearDays: 27.32,
    dayHours: 655.68,
    tiltDeg: 6.68,
    orbitalInclinationDeg: 5.145,
    orbitalAscendingNodeDeg: 125.08,
    texture: "./textures/2k_moon.jpg",
    color: 0xd0d0d0,
    hasOrbitRing: false,
    hasLabel: true,
  },
  {
    name: "Mars",
    kind: "planet",
    visualRole: "planet",

    physicalRadiusKm: 3389.5,
    orbitalDistanceAu: 1.524,
    yearDays: 687,
    dayHours: 24.62,
    tiltDeg: 25.19,
    orbitalInclinationDeg: 1.85,
    orbitalAscendingNodeDeg: 49.558,
    texture: "./textures/2k_mars.jpg",
    color: 0xc96f55,
    hasOrbitRing: true,
    hasLabel: true,
  },

  {
    name: "Asteroid Belt",
    kind: "belt",
    visualRole: "belt",
    innerAu: 2.2,
    outerAu: 3.2,
    thickness: 1.8,
    asteroidScaleMin: 0.01,
    asteroidScaleMax: 0.04,
    verticalSpreadFactor: 0.22,
    radialJitter: 0.12,
    geometryRadius: 1,
    count: 900,
    yearDays: 1800,
    color: 0x8f8476,
    hasOrbitRing: false,
    hasLabel: false,
  },

  {
    name: "Ceres",
    kind: "dwarf",
    visualRole: "dwarf",

    physicalRadiusKm: 473,
    orbitalDistanceAu: 2.77,
    yearDays: 1680,
    dayHours: 9.07,
    tiltDeg: 4,
    orbitalInclinationDeg: 10.6,
    orbitalAscendingNodeDeg: 80.3,
    texture: "./textures/ceres.jpg",
    color: 0xb7b1a3,
    hasOrbitRing: true,
    hasLabel: true,
  },
  {
    name: "Jupiter",
    kind: "planet",
    visualRole: "planet",

    physicalRadiusKm: 69911,
    orbitalDistanceAu: 5.203,
    yearDays: 4331,
    dayHours: 9.93,
    tiltDeg: 3.13,
    orbitalInclinationDeg: 1.303,
    orbitalAscendingNodeDeg: 100.464,
    texture: "./textures/2k_jupiter.jpg",
    color: 0xd2b28a,
    hasOrbitRing: true,
    hasLabel: true,
  },
  {
    name: "Saturn",
    kind: "planet",
    visualRole: "planet",

    physicalRadiusKm: 58232,
    orbitalDistanceAu: 9.537,
    rings: {
      enabled: true,
      innerRadiusRelativeToPlanet: 1.3,
      outerRadiusRelativeToPlanet: 2.1,
      texture: "./textures/saturn_small_ring_tex.png",
      color: 0x443828,
    },
    yearDays: 10747,
    dayHours: 10.7,
    tiltDeg: 26.73,
    orbitalInclinationDeg: 2.489,
    orbitalAscendingNodeDeg: 113.665,
    texture: "./textures/2k_saturn.jpg",
    color: 0xd9c58c,
    hasOrbitRing: true,
    hasLabel: true,
  },
  {
    name: "Uranus",
    kind: "planet",
    visualRole: "planet",

    physicalRadiusKm: 25362,
    orbitalDistanceAu: 19.191,
    yearDays: 30589,
    dayHours: -17.24,
    tiltDeg: 97.77,
    orbitalInclinationDeg: 0.773,
    orbitalAscendingNodeDeg: 74.006,
    texture: "./textures/2k_uranus.jpg",
    color: 0xa5d9e7,
    hasOrbitRing: true,
    hasLabel: true,
  },
  {
    name: "Neptune",
    kind: "planet",
    visualRole: "planet",

    physicalRadiusKm: 24622,
    orbitalDistanceAu: 30.07,
    yearDays: 59800,
    dayHours: 16.11,
    tiltDeg: 28.32,
    orbitalInclinationDeg: 1.77,
    orbitalAscendingNodeDeg: 131.784,
    texture: "./textures/2k_neptune.jpg",
    color: 0x456ddd,
    hasOrbitRing: true,
    hasLabel: true,
  },
  {
    name: "Pluto",
    kind: "dwarf",
    visualRole: "dwarf",

    physicalRadiusKm: 1188.3,
    orbitalDistanceAu: 39.48,
    yearDays: 90560,
    dayHours: -153.3,
    tiltDeg: 119.6,
    orbitalInclinationDeg: 17.1,
    orbitalAscendingNodeDeg: 110.3,
    texture: "./textures/2k_pluto.jpg",
    color: 0xbfae9c,
    hasOrbitRing: true,
    hasLabel: true,
  },
];
/* valeur réel de tiltDeg (inclinaison de l'axe de rotation) pour les objets du système solaire :
Mercury: 0.03
Venus: 177.36
Earth: 23.44
Mars: 25.19
Jupiter: 3.13
Saturn: 26.73
Uranus: 97.77
Neptune: 28.32
Pluto: 119.61
Moon: 6.68
Ceres: 4.0   // approx visuelle, variable selon conventions */
